import { useEffect } from 'react';
import Head from 'next/head'
import { isBrowser } from 'framer-motion';

import { client, query } from '@/config/sanity.config'

import { Header, Projects, ScrollToTopButton, Footer } from '@/components'

import { scrollToTop } from '@/utils';

import { ProjectType } from '@/types/project.type';

type HomeProps = {
  projects: ProjectType[]
}

export default function Home({ projects }: HomeProps) {
  useEffect(() => {
    if (!isBrowser) return;

    window.location.replace("#");
    scrollToTop()

    if (typeof window.history.replaceState == 'function') {
      history.replaceState({}, '', window.location.href.slice(0, -1));
    }
  }, [])

  return (
    <>
      <Head>
        <title>Sam Marxz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />
        <Projects projects={projects} />
        <Footer />
      </>
    </>
  )
}

export async function getStaticProps() {
  const projects = await client.fetch(query)

  return {
    props: {
      projects
    }
  }
}